### ISSUE TITLE
OpenGL хрень

### ISSUE THREAD

**Issue by rominf** [iu7-ray-teamwork/junkcraft#25]
Вот такая хрень сыпется при запуске `python3 __main__.py`:

```
Traceback (most recent call last):
  File "__main__.py", line 9, in <module>
    render(surface, image, math.Matrix.rotate(math.radians(45)) * math.Matrix.translate(0.5, 0))
  File "/data/romas/bmstu/term/8/team_work/junkcraft/engine/_render.py", line 194, in render
    texture, program, vertex_array = get_stuff_for(context, image)
  File "/data/romas/bmstu/term/8/team_work/junkcraft/engine/_render.py", line 156, in get_stuff_for
    Shader(context, GL_FRAGMENT_SHADER, fragment_shader),
  File "/data/romas/bmstu/term/8/team_work/junkcraft/engine/_render.py", line 72, in __init__
    raise Exception(log)
Exception: 0:8(11): error: `gl_FragColor' redeclared
```

OpenGL версии 3.1.0.

**Comment by rominf** [comment]
Наблюдается только в #24, в master всё ОК.

**Comment by yuri-kilochek** [comment]
Подозреваю отсутствие GL 3.3 там где гоняются тесты

**Comment by rominf** [comment]
Поставил последнюю Mesa. И у меня всё равно OpenGL 3.0.

**Comment by rominf** [comment]
@yuri-kilochek. У меня всё равно не работает(

**Comment by yuri-kilochek** [comment]
Запилено в #34
